site_name: AIGC 知识库
site_url: http://docs.workbygpt.com/
site_description: 人工智能领域知识库，专注于AIGC、NLP、机器学习
copyright:
repo_url: https://github.com/netblack/aigc
edit_uri: edit/main/docs/
nav:
  - 技术文档: /
  - 前沿资讯: /news
  - About: about.md
theme: 
  name: readthedocs
  highlightjs: True
copyright: <a href="https://beian.miit.gov.cn" target="_blank">豫ICP备2023023282号-1</a>
