name: argocd-deployment

on:
  release:
    types:
      - published
jobs:
  modify-repo:
    runs-on: ubuntu-latest
    env: 
      GITOPS_REPO_BRANCH: main
    steps:
      - name: GitOps Repo - Checkout
        uses: actions/checkout@v4
        env: 
          GITOPS_REPO_URL: netblack/aigc-monorepo
        with:
          repository: ${{ env.GITOPS_REPO_URL }}
          ref: ${{ env.GITOPS_REPO_BRANCH }}
          fetch-depth: 0
          token: ${{ secrets.PTA }}
      - name: GitOps Repo - Patch and push
        env: 
          GITOPS_REPO_VALUES: values.yaml
          TAG: ${{ github.event.release.tag_name }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          sed -i 's|tag:.*|tag: '$TAG'|' charts/aigc-docs/$GITOPS_REPO_VALUES
          git commit -am "Update tag to '$TAG' in $GITOPS_REPO_VALUES"
          git push origin $GITOPS_REPO_BRANCH